### PR TITLE
Fixes #110: api:environments:domains-clear-varnish not working.

### LINKED ISSUE #110: api:environments:domains-clear-varnish not working
Current acli version

```
$ acli --version
acli v1.0.0-beta1
```

When trying to clear varnish cache, command is faling:

```
$ acli api:environments:domains-clear-varnish 99999-99999999-9999999 --domains=sitename.domain.io,domain2.domain.io

  Too many arguments, expected arguments "command".

api:environments:domains-clear-varnish [--domains DOMAINS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command>
```

The previous error don't indicate uuid / environment id, i tried to ommit that as seen:

```
$ acli api:environments:domains-clear-varnish --domains=sitename.domain.io,domain2.domain.io

  The "environmentId" option does not exist.

api:environments:domains-clear-varnish [--domains DOMAINS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command>
```

Same equivalent command works just fine on ADS

```
ads api:environments:domains-clear-varnish 99999-99999999-9999999 --domains=sitename.domain.io domain2.domain.io
{
  "message": "Varnish is being cleared for the selected domains.",
  "_links": {
    "self": {
      "href": "https://cloud.acquia.com/api/environments/99999-99999999-9999999/domains/actions/clear-varnish"
    },
    "notification": {
      "href": "https://cloud.acquia.com/api/notifications/33333-44444-55555-6666"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

File: src/Command/Api/ApiCommandHelper.php [hunk 1]
```diff
@@ -165,6 +165,9 @@ public function getApiCommands(): array {
         if ($schema['x-cli-name'] === 'accounts:drush-aliases') {
           continue;
         }
+        if ($schema['x-cli-name'] === 'environments:domains-clear-varnish') {
+          $true = TRUE;
```
Comment (grasmash) [inline src/Command/Api/ApiCommandHelper.php:169]: Oops, debug statement left in.
