### PR TITLE
Fixes #307: Regression when refreshing databases.

### LINKED ISSUE #307: Regression when refreshing databases
Ran into the issue by testing HEAD:

```
[debug] Dumping MySQL database to /mnt/tmp/MYSITEtest/acli-mysql-dump-test-MYSITEstg.sql.gz on remote server
/bin/bash: /mnt/tmp/MYSITEtest/acli-mysql-dump-test-MYSITEstg.sql.gz: No such file or directory
   0 B [   0 B/s]
mysqldump: Got errno 32 on write
Connection to MYSITEstg.ssh.prod.acquia-sites.com closed.

In PullCommandBase.php line 220:
                                                  
  [Acquia\Cli\Exception\AcquiaCliException]       
  Could not create database dump on remote host:  
```

It seems related to this path being invalid on the Cloud Platform servers:

```
$ ls /mnt/tmp/MYSITE
MYSITEdev/   MYSITE.dev/  MYSITEstg/   MYSITE.test/
```

See `MYSITE.test` not `MYSITEtest`.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

File: src/Command/Pull/PullCommandBase.php [hunk 1]
```diff
@@ -211,7 +210,13 @@ protected function importRemoteDatabase(
   protected function createRemoteDatabaseDump($environment, $database): array {
     $db_name = $this->getNameFromDatabaseResponse($database);
     $filename = "acli-mysql-dump-{$environment->name}-{$db_name}.sql.gz";
-    $temp_prefix = $database->name . $database->environment->name;
+    if ($this->isAcsfEnv($environment)) {
```
Comment (grasmash) [inline src/Command/Pull/PullCommandBase.php:213]: This conditional can be removed after CXAPI-7819.
