### PR TITLE
Fix #722: Errors linking Cloud application when running non-interactively

### LINKED ISSUE #722: 1.18.0: `acli remote:aliases:download` fails with variety of php errors
Trying to get acli 1.18.0 going with ddev, but having trouble in a test.

auth:login works
```
$ acli auth:login -n --key="${ACQUIA_API_KEY}" --secret="${ACQUIA_API_SECRET}"
Saved credentials to /home/rfay/.acquia/cloud_api.conf
```

remote:aliases:list seems to work (but halts waiting for the choice of 0 or 1)
```
$ acli remote:aliases:list

 Please select a Cloud Platform application: [Alejandro Moreno (Employee Free)]:
  [0] Alejandro Moreno (Employee Free)
  [1] Acquia Cloud Next
 > 0

+----------------------------------+-------------------+--------------------------------------------+
| Application                      | Environment Alias | Environment UUID                           |
+----------------------------------+-------------------+--------------------------------------------+
| Alejandro Moreno (Employee Free) | eeamoreno.dev     | 36120-781af1ee-359f-44a9-8944-652e50500f1b |
| Alejandro Moreno (Employee Free) | eeamoreno.prod    | 36119-781af1ee-359f-44a9-8944-652e50500f1b |
| Alejandro Moreno (Employee Free) | eeamoreno.stg     | 36121-781af1ee-359f-44a9-8944-652e50500f1b |
+----------------------------------+-------------------+--------------------------------------------+
```

But then remote:aliases:download seems to fail dramatically:

```
$ acli remote:aliases:download -n -vvv

Box Requirements Checker
========================

> Using PHP 7.4.23
> PHP is using the following php.ini file:
  /etc/php/7.4/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3 | ^8.0" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "zumba/amplitude-php" requires the extension "curl".


 [OK] Your system is ready to run the application.


Composer script `pre-acli-remote-aliases-download` does not exist in `composer.json`, skipping.
Acquia CLI version: 1.18.0
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.
PHP Notice:  Trying to get property 'id' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 62

Notice: Trying to get property 'id' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 62
PHP Notice:  Trying to get property 'uuid' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 63

Notice: Trying to get property 'uuid' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 63
PHP Notice:  Trying to get property 'name' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 64

Notice: Trying to get property 'name' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 64
PHP Notice:  Trying to get property 'hosting' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 65

Notice: Trying to get property 'hosting' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 65
PHP Notice:  Trying to get property 'subscription' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 66

Notice: Trying to get property 'subscription' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 66
PHP Notice:  Trying to get property 'organization' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 67

Notice: Trying to get property 'organization' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 67
PHP Warning:  First parameter must either be an object or the name of an existing class in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 68

Warning: First parameter must either be an object or the name of an existing class in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 68
PHP Notice:  Trying to get property 'flags' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 71

Notice: Trying to get property 'flags' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 71
PHP Notice:  Trying to get property 'status' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 72

Notice: Trying to get property 'status' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 72
PHP Notice:  Trying to get property '_links' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 73

Notice: Trying to get property '_links' of non-object in phar:///usr/local/bin/acli/vendor/typhonius/acquia-php-sdk-v2/src/Response/ApplicationResponse.php on line 73
PHP Notice:  Trying to get property 'id' of non-object in phar:///usr/local/bin/acli/src/Command/Remote/AliasesDownloadCommand.php on line 51

Notice: Trying to get property 'id' of non-object in phar:///usr/local/bin/acli/src/Command/Remote/AliasesDownloadCommand.php on line 51
PHP Notice:  Undefined offset: 1 in phar:///usr/local/bin/acli/src/Command/Remote/AliasesDownloadCommand.php on line 52

Notice: Undefined offset: 1 in phar:///usr/local/bin/acli/src/Command/Remote/AliasesDownloadCommand.php on line 52
Cloud Platform Drush Aliases archive downloaded to /tmp/AcquiaDrushAliasesV8BIs6.tar.gz

In AliasesDownloadCommand.php line 83:

  [Acquia\Cli\Exception\AcquiaCliException]
  Could not locate any aliases matching the current site ()


Exception trace:
  at phar:///usr/local/bin/acli/src/Command/Remote/AliasesDownloadCommand.php:83
 Acquia\Cli\Command\Remote\AliasesDownloadCommand->execute() at phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:428
 Acquia\Cli\Command\CommandBase->run() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:996
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/acli/bin/acli:69
 require() at /usr/local/bin/acli:14

remote:aliases:download
```

### PR DESCRIPTION
**Pull request by danepowell**
**Motivation**

Fixes #722

**Proposed changes**
Throw an exception any time a command requires a linked application, but no application is provided or found.

**Testing steps**
1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. Find a Drupal site that's _not_ linked to a Cloud app
4. Run a command requiring a linked application non-interactively, i.e. `acli remote:aliases:download -n -vvv`
5. Expect a clear exception rather than a bunch of PHP errors.

**Merge requirements**
- [x] _Bug_, _enhancement_, or _breaking change_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

File: src/Command/CommandBase.php [hunk 1]
```diff
@@ -812,16 +812,18 @@ protected function determineCloudEnvironment() {
...
-      $application = $this->getCloudApplication($application_uuid);
-      // No point in trying to link a directory that's not a repo.
-      if (!empty($this->repoRoot) && !$this->getCloudUuidFromDatastore()) {
-        if ($prompt_link_app) {
-          $this->saveCloudUuidToDatastore($application);
-        }
-        elseif (!AcquiaDrupalEnvironmentDetector::isAhIdeEnv() && !$this->getCloudApplicationUuidFromBltYaml()) {
-          $this->promptLinkApplication($application);
-        }
+    if (!isset($application_uuid)) {
```
Comment (danepowell) [inline src/Command/CommandBase.php:815]: This looks like a big diff but it's really just adding a guard conditional.

File: src/Command/Ide/IdeOpenCommand.php [hunk 2]
```diff
@@ -35,9 +35,6 @@ protected function configure() {
   protected function execute(InputInterface $input, OutputInterface $output) {
     $acquia_cloud_client = $this->cloudApiClientService->getClient();
     $cloud_application_uuid = $this->determineCloudApplication();
-    if (!$cloud_application_uuid && !$input->isInteractive()) {
-      throw new RuntimeException('Not enough arguments (missing: "applicationUuid").');
```
Comment (danepowell) [inline src/Command/Ide/IdeOpenCommand.php:39]: This is the only place in the codebase where the command validates that an application was found. I think it's safe to assume that if any command calls `determineCloudApplication()`, an application _must_ be found or an exception thrown.

**Comment by danepowell** [comment]
@grasmash @anavarre ready for your review
