### PR TITLE
CLI-857: Warning on missing refresh token

### LINKED ISSUE #1177: CLI-857: Check refresh tokens files in IDE before pulling the app
I'm seeing this issue when testing Cloud IDE locally. This is because ACLI's now looking for refresh token files.

```
ide:~/project $ acli pull

Warning: file_get_contents(/usr/local/share/ide/.accesstoken): Failed to open stream: No such file or directory in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php on line 33

Warning: file_get_contents(/usr/local/share/ide/.expirytoken): Failed to open stream: No such file or directory in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php on line 48
```

In the context of the IDE, we should likely check those files exist, then default to `acquia_cli.conf`, then fail with an authentication issue message.

### PR DESCRIPTION
**Pull request by danepowell**
**Motivation**

Fixes #1177

**Proposed changes**

Catch this condition and rethrow as an exception so we can track via Amplitude and provide the customer with assistance

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment or [download a pre-built acli.phar](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#automatic-dev-builds) for this PR.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. Set ACLI_ACCESS_TOKEN_FILE or ACLI_ACCESS_TOKEN_EXPIRY_FILE to an invalid value and observe that an exception is thrown instead of a warning.

### CODE REVIEW

File: src/CloudApi/CloudCredentials.php [hunk 1]
```diff
@@ -23,29 +24,37 @@ public function __construct(CloudDataStore $datastoreCloud) {
...
-      return getenv('ACLI_ACCESS_TOKEN');
+    if ($token = getenv('ACLI_ACCESS_TOKEN')) {
+      return $token;
     }
 
-    if (getenv('ACLI_ACCESS_TOKEN_FILE')) {
-      return trim(file_get_contents(getenv('ACLI_ACCESS_TOKEN_FILE')), "\"\n");
+    if ($file = getenv('ACLI_ACCESS_TOKEN_FILE')) {
+      if (!file_exists($file)) {
+        throw new AcquiaCliException('Access token file not found at {file}', ['file' => $file]);
```
Comment (danepowell) [inline src/CloudApi/CloudCredentials.php:36]: @anavarre let me know if you want me to add a link to a known issue or any other information here

Comment (anavarre) [reply src/CloudApi/CloudCredentials.php:36]: Linked in the Jira ticket.
