### PR TITLE
Fix #403: Commands that invoke auth:login fail to pick up new credentials

### LINKED ISSUE #403: Critical regression in acli ide:wizard:ssh-key:create-upload mistakenly indicating API creds are wrong
In Cloud IDE, when running `acli ide:wizard:ssh-key:create-upload` for the very first time in a brand new IDE, the command will mistakenly return creds are invalid even though they are valid. Upon running the same exact command again, you'll immediately pass through the auth and the key will be updated immediately.

```
ide:~/project $ acli ide:wizard:ssh-key:create-upload -vvv

Box Requirements Checker
========================

> Using PHP 7.3.21
> PHP is using the following php.ini file:
  /usr/local/php7.3/etc/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3 | ^8.0" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

Acquia CLI version: 1.4.0
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Would you like to share anonymous performance usage and data? (yes/no) [yes]:
 > no

Ok, no data will be collected and shared with us.
We take privacy seriously.
If you change your mind, run acli telemetry.
You will need a Cloud Platform API token from https://cloud.acquia.com/a/profile/tokens

 Please enter your API Key:
 > REDACTED

Please enter your API Secret: 
Saved credentials to /home/ide/.acquia/cloud_api.conf
Acquia CLI version: 1.4.0

In ExceptionListener.php line 34:
                                                                                       
  [Acquia\Cli\Exception\AcquiaCliException (1)]                                        
  Your Cloud Platform API credentials are invalid. Run acli auth:login to reset them.  
                                                                                       

Exception trace:
  at phar:///opt/local/acli/src/EventListener/ExceptionListener.php:34
 Acquia\Cli\EventListener\ExceptionListener->onConsoleError() at phar:///opt/local/acli/vendor/symfony/event-dispatcher/EventDispatcher.php:270
 Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}() at phar:///opt/local/acli/vendor/symfony/event-dispatcher/EventDispatcher.php:230
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at phar:///opt/local/acli/vendor/symfony/event-dispatcher/EventDispatcher.php:59
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at phar:///opt/local/acli/vendor/symfony/console/Application.php:995
 Symfony\Component\Console\Application->doRunCommand() at phar:///opt/local/acli/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at phar:///opt/local/acli/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at phar:///opt/local/acli/bin/acli:88
 require() at /opt/local/acli:14

ide:wizard:ssh-key:create-upload

ide:~/project $ acli ide:wizard:ssh-key:create-upload -vvv

Box Requirements Checker
========================

> Using PHP 7.3.21
> PHP is using the following php.ini file:
  /usr/local/php7.3/etc/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3 | ^8.0" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

Acquia CLI version: 1.4.0
    ✔ Creating a local SSH key
    ✔ Uploading the local key to the Cloud Platform
    ✔ Adding the SSH key to local keychain
    ⠹ Waiting for the key to become available on the Cloud Platform
[debug] Permission denied (publickey).
    ⠹ Waiting for the key to become available on the Cloud Platform
[debug] Permission denied (publickey).
    ⠹ Waiting for the key to become available on the Cloud Platform
[debug] Permission denied (publickey).
    ✔ Waiting for the key to become available on the Cloud Platform

Your SSH key is ready for use!

```

I consider it critical because the first experience working with Acquia CLI and Cloud IDE is very confusing and misleading.

### PR DESCRIPTION
**Pull request by danepowell**
Motivation
----------
Fixes #403

Proposed changes
---------
auth:login should re-initialize the Typhonius Connector client service with the new credentials (otherwise it will use whatever was read at the start of the process)

This normally is not a problem since invoking one ACLI command in another is rare. `ide:wizard` is the only command I could find that invokes `auth:login`.

Testing steps
---------
How can we replicate the issue and verify that this PR fixes it?

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `acli ckc`
3. Clear your Acquia credentials
4. Run `ide:wizard`

### CODE REVIEW

File: src/Command/Auth/AuthLoginCommand.php [hunk 1]
```diff
@@ -60,7 +61,9 @@ protected function execute(InputInterface $input, OutputInterface $output) {
     $api_key = $this->determineApiKey($input, $output);
     $api_secret = $this->determineApiSecret($input, $output);
     $this->writeApiCredentialsToDisk($api_key, $api_secret);
-
+    // Client service needs to be reinitialized with new credentials in case
+    // this is being run as a sub-command.
```
Comment (grasmash) [inline src/Command/Auth/AuthLoginCommand.php:65]:
```suggestion
    // this is being run as a sub-command.
    // @see https://github.com/acquia/cli/issues/403
```

**Review by grasmash — APPROVED** [review]

**Review by anavarre — APPROVED** [review]
Manual test looks good:

```
ide:/tmp/cli (danepowell/issue-403) $ ./bin/acli ckc
ide:/tmp/cli (danepowell/issue-403) $ ./bin/acli ide:wizard
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Would you like to share anonymous performance usage and data? (yes/no) [yes]:
 > no

Ok, no data will be collected and shared with us.
We take privacy seriously.
If you change your mind, run acli telemetry.
You will need a Cloud Platform API token from https://cloud.acquia.com/a/profile/tokens

Please enter your API Key:
> REDACTED

Please enter your API Secret: 
Saved credentials to /home/ide/.acquia/cloud_api.conf
    ✔ Creating a local SSH key
    ✔ Uploading the local key to the Cloud Platform
    ✔ Adding the SSH key to local keychain
    ✔ Waiting for the key to become available on the Cloud Platform

Your SSH key is ready for use!
```
